// LOGIN
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const REMOVE_EXPENSESOFCATEGORY = 'REMOVE_EXPENSESOFCATEGORY'
export const REMOVE_INCOMEOFCATEGORY = 'REMOVE_INCOMEOFCATEGORY'

// STATS
export const LOAD_CATEGORIES_BREAKDOWN = 'LOAD_CATEGORIES_BREAKDOWN'
export const LOAD_EXPENSES_BREAKDOWN = 'LOAD_EXPENSES_BREAKDOWN'
export const LOAD_INCOME_BREAKDOWN = 'LOAD_INCOME_BREAKDOWN'
export const EDIT_STATISTICS = 'EDIT_STATISTICS'
export const CREATE_NEWCATEGORY_STATISTICS = 'CREATE_NEWCATEGORY_STATISTICS'
export const EDIT_CATEGORY_STATISTICS = 'EDIT_CATEGORY_STATISTICS'
export const DELETE_CATEGORY_STATISTICS = 'DELETE_CATEGORY_STATISTICS'

// ALERT
export const ADD_ALERT = 'ADD_ALERT'

// LOADING
export const TOGGLE_LOADING = 'TOGGLE_LOADING'
