
// STATS
export const SET_CATEGORIES_BREAKDOWN = 'SET_CATEGORIES_BREAKDOWN'
export const UPDATE_STATISTICS = 'UPDATE_STATISTICS'
export const ADD_NEWCATEGORY_STATISTICS = 'ADD_NEWCATEGORY_STATISTICS'
export const UPDATE_CATEGORY_STATISTICS = 'UPDATE_CATEGORY_STATISTICS'
export const REMOVE_CATEGORY_STATISTICS = 'REMOVE_CATEGORY_STATISTICS'

// ALERT
export const CREATE_ALERT = 'CREATE_ALERT'

// LOADING
export const UPDATE_LOADING = 'UPDATE_LOADING'
